#
# Copyright 2018 The Feast Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
grpc:
  server:
    port: ${FEAST_CORE_GRPC_PORT:6565}
    address: ${FEAST_CORE_GRPC_ADDRESS:0.0.0.0}

server:
  port: ${FEAST_CORE_HTTP_PORT:8080}

feast:
  jobConfig:
    coreApiUrl: ${FEAST_JOBS_CORE_API_URL:localhost:6565}
    runner: ${FEAST_JOBS_RUNNER:DirectRunner}
#    options:
#      projectId: my-dataflow-project
#      region: my-dataflow-location
    executable: ${FEAST_JOBS_EXECUTABLE:feast-ingestion.jar}
    errorsStoreType: ${FEAST_JOBS_ERRORS_STORE_TYPE:stdout}
#      errorsStoreOptions:
#        path: gs://my-errors-store-bucket
    monitoringPeriod: ${FEAST_JOBS_MONITORING_PERIOD:5000}
    monitoringInitialDelay: ${FEAST_JOBS_MONITORING_INIT_DELAY:60000}
  statsd:
    enabled: ${FEAST_STATSD_ENABLED:true}
    host: ${FEAST_STATSD_HOST:localhost}
    port: ${FEAST_STATSD_PORT:8125}


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

management:
  metrics:
    export:
      simple:
        enabled: false
      statsd:
        enabled: ${feast.statsd.enabled}
        host: ${feast.statsd.host}
        port: ${feast.statsd.port}