grpc:
  server:
    port: 6565
    address: 0.0.0.0
http:
  server:
    port: 8080

feast:
  jobConfig:
    coreApiUrl: localhost:6565
    runner: DirectRunner
#    options:
#      projectId: my-dataflow-project
#      region: my-dataflow-location
    executable: feast-ingestion.jar
    errorsStoreType: stdout
#      errorsStoreOptions:
#        path: gs://my-errors-store-bucket
    monitoringPeriod: 5000
    monitoringInitialDelay: 60000
  statsd:
    enabled: true
    host: localhost
    port: 8125


spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

management:
  metrics:
    export:
      simple:
        enabled: false
      statsd:
        enabled: ${feast.statsd.enabled}
        host: ${feast.statsd.host}
        port: ${feast.statsd.port}